dag:
  - name: base
    dependencies:
      - name: mongodb
      - name: redis
      - name: redisui
      - name: kafka
      - name: kafka-ui
      - name: kafkainitpod

  - name: identity
    dependencies:
       - name: identity
         dependencies:
           - name: mongodb
           - name: redis
           - name: kafka

config:
    - openlm_config_generic
    - openlm_logging_config_generic
    - openlm_telemetry_config_generic
