dag:
  - name: infra
    dependencies:
      - name: mongodb
      - name: redis
      - name: redisui
      - name: kafka
      - name: kafka-ui
      - name: kafkainitpod

  - name: identity
    dependencies:
       - name: identity
         dependencies:
           - name: mongodb
           - name: redis
           - name: kafka

config:
    - openlm-config-generic
    - openlm-logging-config-generic
    - openlm-telemetry-config-generic
