apiVersion: v1
kind: Service
metadata:
  #annotations:
    #field.cattle.io/targetWorkloadIds: '["openlm/openlm-identityapi"]'
    #management.cattle.io/ui-managed: 'true'
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: {{ .Values.service.ports.name }}
      port: {{ .Values.service.ports.port }}
      protocol: TCP
      targetPort: {{ .Values.service.ports.targetPort }}
  selector:
    app.kubernetes.io/name: apps.deployment-openlm-{{ .Values.deployment.name | default .Values.service.name }}
  type: ClusterIP
